export const ACTIONS = {
    //gateway's actions
    CREATE_GATEWAY : "CREATE_GATEWAY",
    RETRIEVE_GATEWAYS : "RETRIEVE_GATEWAYS",
    RETRIEVE_GATEWAY : "RETRIEVE_GATEWAY",
    UPDATE_GATEWAY : "UPDATE_GATEWAY",
    DELETE_GATEWAY : "DELETE_GATEWAY",

    //device's actions
    CREATE_DEVICE : "CREATE_DEVICE",
    RETRIEVE_DEVICES : "RETRIEVE_DEVICES",
    RETRIEVE_DEVICE : "RETRIEVE_DEVICE",
    UPDATE_DEVICE : "UPDATE_DEVICE",
    DELETE_DEVICE : "DELETE_DEVICE",
}